db_user="root"
db_passwd = "ILoveData4!"
API_KEY = "pk.eyJ1IjoiaGxlZWs0MCIsImEiOiJjanY5bXl3dWQxMzg1NGRudDk3YnQ2cXNuIn0.GJIFOTMSb-Fm_O5oGw17sQ"
db_name = "bike_crash_db"
host = "localhost"
port = "3306"
