db_user="root"
db_passwd = "bigt1t"
API_KEY = "pk.eyJ1Ijoia2NzMzQya2NzIiwiYSI6ImNqdjlpbGlrNjEyYmszeW1lNm15Nm50M2wifQ.tHtuPXtbJ31K-p0velENgw"
db_name = "bike_crash_db"
host = "localhost"
port = "3306"
